// <auto-generated />
using System;
using Biura.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biura.DAL.Migrations
{
    [DbContext(typeof(BiuraDbContext))]
    [Migration("20251218151716_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Biura.Model.Agency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("Biura.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RegistryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegistryId");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Biura.Model.Excursion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("People")
                        .HasColumnType("int");

                    b.Property<int>("TripOperatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripOperatorId");

                    b.ToTable("Excursion");
                });

            modelBuilder.Entity("Biura.Model.Insurance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("ComissionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CoverageEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CoverageStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("Insurance");
                });

            modelBuilder.Entity("Biura.Model.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgencyId")
                        .HasColumnType("int");

                    b.Property<decimal>("CommisionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("Biura.Model.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("Biura.Model.Registry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AdditionalPayment")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("AfterpaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("AfterpaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("AgencyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FlightConfirmationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("InitialPaymentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InsuranceDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("TripDetailsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AfterpaymentId");

                    b.HasIndex("AgencyId");

                    b.HasIndex("InitialPaymentId");

                    b.HasIndex("InsuranceDetailsId");

                    b.HasIndex("TripDetailsId");

                    b.ToTable("Registries");
                });

            modelBuilder.Entity("Biura.Model.Client", b =>
                {
                    b.HasOne("Biura.Model.Registry", null)
                        .WithMany("Clients")
                        .HasForeignKey("RegistryId");
                });

            modelBuilder.Entity("Biura.Model.Excursion", b =>
                {
                    b.HasOne("Biura.Model.Operator", "TripOperator")
                        .WithMany("Excursions")
                        .HasForeignKey("TripOperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripOperator");
                });

            modelBuilder.Entity("Biura.Model.Insurance", b =>
                {
                    b.HasOne("Biura.Model.Agency", null)
                        .WithMany("Insurances")
                        .HasForeignKey("AgencyId");
                });

            modelBuilder.Entity("Biura.Model.Operator", b =>
                {
                    b.HasOne("Biura.Model.Agency", null)
                        .WithMany("TourOperators")
                        .HasForeignKey("AgencyId");
                });

            modelBuilder.Entity("Biura.Model.Registry", b =>
                {
                    b.HasOne("Biura.Model.Payment", "Afterpayment")
                        .WithMany()
                        .HasForeignKey("AfterpaymentId");

                    b.HasOne("Biura.Model.Agency", null)
                        .WithMany("Registries")
                        .HasForeignKey("AgencyId");

                    b.HasOne("Biura.Model.Payment", "InitialPayment")
                        .WithMany()
                        .HasForeignKey("InitialPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biura.Model.Insurance", "InsuranceDetails")
                        .WithMany()
                        .HasForeignKey("InsuranceDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Biura.Model.Excursion", "TripDetails")
                        .WithMany()
                        .HasForeignKey("TripDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Afterpayment");

                    b.Navigation("InitialPayment");

                    b.Navigation("InsuranceDetails");

                    b.Navigation("TripDetails");
                });

            modelBuilder.Entity("Biura.Model.Agency", b =>
                {
                    b.Navigation("Insurances");

                    b.Navigation("Registries");

                    b.Navigation("TourOperators");
                });

            modelBuilder.Entity("Biura.Model.Operator", b =>
                {
                    b.Navigation("Excursions");
                });

            modelBuilder.Entity("Biura.Model.Registry", b =>
                {
                    b.Navigation("Clients");
                });
#pragma warning restore 612, 618
        }
    }
}
